[package]
name = "cardwire-tray"
version = "0.4.0"
edition = "2024"

[dependencies]
futures-util = "0.3.32"
ksni = "0.3.4"
notify-rust = "4.17.0"
rfd = "0.17.2"
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread", "sync", "time"] }
zbus = { version = "5.15.0", features = ["tokio"] }
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1", features = ["derive"] }
semver = "1"
anyhow = "1"
iced = { version = "0.13.1", features = ["tokio", "auto-detect-theme"] }
toml = "0.9"
dark-light = "1.1.1"
